### ISSUE TITLE
"conjunctive" operators and the Boolean section

### ISSUE THREAD

**Issue by gezeta-id** [alhassy/JavaScriptCheatSheet#4]
In the _Booleans_ section a bullet point says:

> Note: `(p < q < r) ≈ (p < q) < r`, it is not conjunctive!

This doesn't seem to be correctly worded. The word _conjunctive_ doesn't seem appropriate there. Also, this applies to most other operators, e.g. `a == b == c` or `a !== b == c`.

In general I don't think this note makes sense here in the _Booleans_ section. It would make a lot more sense to have a section on _Operators_.

**Comment by alhassy** [comment]
In maths, `<` is conjunctive and I was pointing out that this is not the case in JS. Indeed, as the remark points out, `<` is left-associative.

I agree with you that it may be prudent to have a new section on operators ---I only spent about a week learning JS and made the cheat sheet.

For now, I'll close this commit ---since the word choice is intentional, but apparently not optimal. PRs are always welcome.

Thanks!
